language: objective-c
osx_image: xcode9.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
install:
  - brew update
  - brew upgrade carthage
  # CocoaPods
  - pod install
  # Carthage
  - carthage bootstrap
  # Update fastlane
  - gem install fastlane -v '2.79.0'
script:
  - xcrun simctl erase all
  - fastlane scan --devices "iPhone 8 (11.2)" --clean
  - fastlane scan --devices "iPhone 7 (10.3)" --clean
  - fastlane scan --devices "iPhone 4s (9.3)" --clean


after_success:
  - sleep 5
