language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - env: NAME="ably-iOS" LANE=test_iOS12
    - env: NAME="ably-iOS" LANE=test_iOS11
    - env: NAME="ably-iOS" LANE=test_iOS10
    - env: NAME="ably-iOS" LANE=test_iOS9
before_install:
  - gem install cocoapods -v '1.5.3'
  - pod repo update > /dev/null
install:
  # CocoaPods
  - pod install
  # Carthage
  - carthage bootstrap --platform iOS
  # Update fastlane
  - gem install fastlane -v '2.100.1'
before_script:
  - xcrun simctl erase all
script:
  - export ABLY_ENV="idempotent-dev"
  - fastlane $LANE
after_success:
  - sleep 5
