language: objective-c
osx_image: xcode9.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
install:
  - brew update
  - brew upgrade carthage
  # CocoaPods
  - pod install
  # Carthage
  - carthage bootstrap
  # Update fastlane
  - gem install fastlane -v '2.80.0'
script:
  - xcrun simctl erase all
  - fastlane test_iOS11
  - xcrun simctl erase all
  - fastlane test_iOS10
  - xcrun simctl erase all
  - fastlane test_iOS9

after_success:
  - sleep 5
