language: objective-c
osx_image: xcode9.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - iOS11=test_iOS11
    - iOS10=test_iOS10
    - iOS9=test_iOS9
before_install:
  - gem install cocoapods -v '1.4.0'
install:
  - brew update
  - brew upgrade carthage
  # CocoaPods
  - pod install
  # Carthage
  - carthage bootstrap
  # Update fastlane
  - gem install fastlane -v '2.80.0'
before_script:
  - xcrun simctl erase all
script:
  ./Scripts/run_travis_tests.sh
after_success:
  - sleep 5
