language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - env: NAME="ably-iOS" LANE=test_iOS12
    - env: NAME="ably-iOS" LANE=test_iOS11
    - env: NAME="ably-iOS" LANE=test_iOS10
    - env: NAME="ably-iOS" LANE=test_iOS9
    - env: NAME="ably-macOS" LANE=test_macOS
install:
  # Carthage
  - carthage bootstrap --platform iOS
  - carthage bootstrap --platform macOS
  # Update fastlane
  - gem install fastlane -v '2.108.0'
before_script:
  - xcrun simctl erase all
script:
  - export ABLY_ENV="sandbox"
  - fastlane $LANE
after_success:
  - sleep 5
